#!/usr/bin/python3

from argparse import ArgumentParser
import calendar as cal
from datetime import date
from sys import exit

cyan        = "\x1b[36m"
light_red   = "\x1b[91m"
bold_white  = "\x1b[1;37m"
bold_yellow = "\x1b[1;33m"
def colored(text, attr): return attr + text + "\x1b[0m"

parser = ArgumentParser()
parser.add_argument("-1", action="store_true", help="show current month (the default)")
parser.add_argument("-3", dest="q", action="store_true", help="show prior, current, and next month")
parser.add_argument("-m", action="store_true", help="weeks start on Monday")
parser.add_argument("-n", action="store_true", help="simulate ncal (vertical) format")
parser.add_argument("-y", action="store_true", help="show full year")
parser.add_argument("month", nargs='?', help="specify month (eg, Apr, April or 4)")
parser.add_argument("year", nargs='?', help="specify year")

args = parser.parse_args()
cal.setfirstweekday(cal.MONDAY if args.m else cal.SUNDAY)
today = date.today()

####################
def parse_month(month):
    try: n = int(month)
    except ValueError:
        try: n = [ v.lower() for v in cal.month_name ].index(month.lower())
        except ValueError:
            try: n = [ v.lower() for v in cal.month_abbr ].index(month.lower())
            except ValueError: n = -1
    return n

def parse_month_year(args):
    if not args.year:
        if not args.month: return today.month, today.year

        my = parse_month(args.month)
        if my < 1: exit("Neither valid month nor year: " + args.month)
        return (today.month, my) if my > 12 else (my, today.year)

    month = parse_month(args.month)
    if month < 1 or month > 12: exit("Invalid month: " + args.month)

    try: year = int(args.year)
    except ValueError: year = -1
    if year < 1: exit("Invalid year: " + args.year)

    return month, year

####################
def gen_day(day, month, year):
    if not day: return "  "
    d = str(day).rjust(2)
    when = date(year, month, day)
    if when == today: return colored(d, bold_yellow)
    if when.weekday() == cal.SUNDAY: return colored(d, light_red)
    return d

def gen_week_head():
    head = cal.weekheader(2).split(' ')
    return [ colored(h, cyan) for h in head ]

def gen_month(month, year, width, show_year, vertical, col):
    month = cal.month_name[month]
    if show_year: month += ' ' + str(year)
    if vertical: month = ((" " if col else "    ") + month).ljust(width)
    else: month = month.center(width)
    return colored(month, bold_white)

def gen_year(year, width):
    return colored(str(year).center(width), bold_white)

def gen_grid(month, year, show_week, vertical):
    grid = cal.monthcalendar(year, month)
    grid = [ [ gen_day(day, month, year) for day in week ] for week in grid ]
    if show_week: grid.insert(0, gen_week_head())
    if vertical: grid = [ list(row) for row in zip(*grid) ]
    return grid

####################
month, year = parse_month_year(args)
vertical = args.n

if args.y:
    grid_data = [ (month, year) for month in range(1, 13) ]
    year_head = True
    ncol = 4 if vertical else 3
elif args.q:
    grid_data = [ ((m-1) % 12 + 1, year + (m-1) // 12) for m in (month-1, month, month+1) ]
    year_head = not vertical
    ncol = 3
else:
    grid_data = [ (month, year) ]
    year_head = False
    ncol = 1

grid = [ gen_grid(
    month, year, show_week=not vertical or (i % ncol == 0), vertical=vertical
) for i, (month, year) in enumerate(grid_data) ]

cell_width = [ len(cell[0]) * 3 - 1 for cell in grid ]
col_width  = [ max(cell_width[c : : ncol]) for c in range(ncol) ]

cell_height= [ len(cell) for cell in grid ]
row_height = [ max(cell_height[r : r + ncol]) for r in range(0, len(grid), ncol) ]

if year_head:
    width = sum(col_width) + 2 * len(col_width) - 2
    print(gen_year(year, width))

for sec in range(0, len(grid), ncol):
    if sec: print()

    data = [ gen_month(
        *grid_data[sec + col], width, show_year=not year_head, vertical=vertical, col=col
    ) for col, width in enumerate(col_width) ]
    print("  ".join(data))

    for row in range(row_height[sec // ncol]):
        data = []
        for col, width in enumerate(col_width):
            i = sec + col
            s = ' '.join(grid[i][row]) if row < cell_height[i] else ""
            data.append(s + ' ' * (width - cell_width[i] if s else width))
        print("  ".join(data))
